[tools]
azure-kubelogin = "0.2.16"
crane = "0.21.2"
fnox = "1.18.0"
helm = "4.1.3"
kubectl = "1.35.2"
pnpm = "10.32.1"

[tasks."aspire:publish"]
run = "aspire publish -p WCM.API.AppHost -c Release -o ./dist"
alias = "app"
env = { ASPNETCORE_ENVIRONMENT = "Production" }

[tasks."aspire:deploy"]
run = "aspire deploy"
alias = "apd"
