{{- if and .Values.postgresql.enabled (not .Values.openchoreo.enabled) (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wcm-api.fullname" . }}-postgresql
  labels:
    {{- include "wcm-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-password: {{ include "wcm-api.postgresql.password" . | quote }}
{{- end }}
