{{- if not (or .Values.openchoreo.enabled (include "wcm-api.postgresql.isPasswordless" .) (and (not .Values.postgresql.enabled) .Values.externalDatabase.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wcm-api.fullname" . }}
  labels:
    {{- include "wcm-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  WCMDB_PASSWORD: {{ include "wcm-api.postgresql.password" . | quote }}
  ConnectionStrings__wcmdb: {{ include "wcm-api.postgresql.connectionString" . | quote }}
  WCMDB_URI: "postgresql://{{ include "wcm-api.postgresql.username" . }}:{{ include "wcm-api.postgresql.password" . }}@{{ include "wcm-api.postgresql.host" . }}:{{ include "wcm-api.postgresql.port" . }}/{{ include "wcm-api.postgresql.database" . }}"
{{- end }}
