{{- if and .Values.serviceAccount.create (not .Values.openchoreo.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wcm-api.serviceAccountName" . }}
  labels:
    {{- include "wcm-api.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if and (include "wcm-api.postgresql.isPasswordless" .) .Values.workloadIdentity.clientId }}
  {{- $_ := set $annotations "azure.workload.identity/client-id" .Values.workloadIdentity.clientId }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  {{- $annotations = merge $annotations . }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
