apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: wcm-api-buildpacks
  namespace: urbaser
  annotations:
    openchoreo.dev/display-name: "WCM API (Buildpacks)"
    openchoreo.dev/description: "Source build using Paketo .NET buildpack"
spec:
  owner:
    projectName: urbaser
  componentType:
    kind: ClusterComponentType
    name: deployment/service-subdomain
  autoDeploy: true
  workflow:
    kind: ClusterWorkflow
    name: paketo-buildpacks-builder
    parameters:
      repository:
        url: "https://github.com/Urbaser-S-A/WasteContainerManagement.API"
        revision:
          branch: "main"
        appPath: "/"
        secretRef: github-wcm-api
      buildEnv:
        - name: BP_DOTNET_PROJECT_PATH
          value: "WCM.API.ApiService"
