apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: wcm-api-buildpacks-dev
  namespace: urbaser
spec:
  owner:
    projectName: urbaser
    componentName: wcm-api-buildpacks
  environment: dev
  componentTypeEnvironmentConfigs:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
