apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: github-wcm-api
  namespace: default
spec:
  refreshInterval: 1h
  template:
    type: kubernetes.io/basic-auth
  data:
    - secretKey: password
      remoteRef:
        key: github-pat-wcm
