FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/dotnet-sdk:latest@sha256:3b85ed71b772accd27035860b7c65b18bdc93c12b05c974c494eee361a632f83 AS build

ARG TARGETARCH="amd64"
ARG BASE="WCM.API"
ARG TARGETPROJECT="WCM.API.ApiService"

WORKDIR /src

COPY --chown=65532:65532 "$BASE.ServiceDefaults" ./$BASE.ServiceDefaults/
COPY --chown=65532:65532 $TARGETPROJECT ./$TARGETPROJECT/
COPY --chown=65532:65532 Directory.Build.props ./
COPY --chown=65532:65532 *.slnx ./

RUN --mount=type=cache,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/v3-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugins-cache \
    --mount=type=cache,target=/tmp/NuGetScratchroot \
    dotnet restore -a $TARGETARCH "$TARGETPROJECT/$TARGETPROJECT.csproj"


RUN --mount=type=cache,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/v3-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugins-cache \
    --mount=type=cache,target=/tmp/NuGetScratchroot \
    dotnet publish "$TARGETPROJECT/$TARGETPROJECT.csproj" \
    --no-restore \
    --configuration Release \
    --output dist/publish

# Final stage    
FROM cgr.dev/chainguard/aspnet-runtime:latest@sha256:b025e94d1f5f6c060e706af57ad258da187bbe412b2a03a720dcaf8c6cffec8b AS final

WORKDIR /app

COPY --from=build src/dist/publish .

ENV DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_EnableDiagnostics=0 \
    HTTP_PORT=8080 \
    ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "WCM.API.ApiService.dll"]