FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/dotnet-sdk:latest-dev@sha256:ec837aa657c96c7f5f99c13bcece0f196fe990e90be305ee4f63f4c699bf2aa7 AS build

ARG TARGETARCH="amd64"
ARG BASE="WCM.API"
ARG TARGETPROJECT="WCM.API.ApiService"

WORKDIR /src

COPY --chown=65532:65532 "$BASE.ServiceDefaults" ./$BASE.ServiceDefaults/
COPY --chown=65532:65532 $TARGETPROJECT ./$TARGETPROJECT/
COPY --chown=65532:65532 Directory.Build.props ./
COPY --chown=65532:65532 *.slnx ./

RUN --mount=type=cache,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/v3-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugins-cache \
    --mount=type=cache,target=/tmp/NuGetScratchroot \
    dotnet restore -a $TARGETARCH "$TARGETPROJECT/$TARGETPROJECT.csproj"


RUN --mount=type=cache,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/v3-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugins-cache \
    --mount=type=cache,target=/tmp/NuGetScratchroot \
    dotnet publish "$TARGETPROJECT/$TARGETPROJECT.csproj" \
    --no-restore \
    --configuration Release \
    --output dist/publish
# Final stage    
FROM cgr.dev/chainguard/aspnet-runtime:latest-dev@sha256:dc2cb3275ecfdc85e954e129aa975b50f36d5ab0e198ccf658dac2d661fe6e12 AS final

WORKDIR /app

COPY --from=build src/dist/publish .

ENV DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_EnableDiagnostics=0 \
    HTTP_PORT=8080 \
    ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "WCM.API.ApiService.dll"]